In [2]:
# Numpy
import numpy as np
a=np.array([5,5,5,5,5,5])
a

array([5, 5, 5, 5, 5, 5])

In [3]:
# Numpy
import numpy as np
a=np.array([5,5,5]) #(a vector refer  to an array with 1 dimension,there is no difference between row and column vectors)
a

array([5, 5, 5])

In [4]:
type(a) # ndarray is used to represent both vectors and matrixes

numpy.ndarray

In [7]:
# list of lists
import numpy as np
b=np.array([[5,5,5],[5,5,5],[5,5,5]]) #(a matrix refer  to an array with two dimensions)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [8]:
len(b)

3

In [9]:
a[0]

5

In [14]:
a[1]

5

In [15]:
b[2]

array([5, 5, 5])

In [17]:
len(a)

3

In [ ]:
# for 3D or higher dimensional array, term tensor is also commonly used
#(i,j,k)

# array attributes
- dimensions are called axes

In [18]:
import numpy as np
c=np.array([[5,5,5],[5,5,5]])# (2-axes: first axes has length 2,second axes has length 3)
c

array([[5, 5, 5],
       [5, 5, 5]])

In [19]:
import numpy as np
d=np.array([1,2,3,4,5])# (2-axes: first axes has length 2,second axes has length 3)
d

array([1, 2, 3, 4, 5])

In [21]:
e=np.zeros(2)
e

array([0., 0.])

In [22]:
f=np.ones(3)
f

array([1., 1., 1.])

In [23]:
# creat an empty array with two elements
g=np.empty(3)
g

array([1., 1., 1.])

In [24]:
h=np.arange(5)
h

array([0, 1, 2, 3, 4])

In [25]:
k=np.arange(2,20)
k

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [26]:
q=np.arange(2,20,2)
q

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
# linearly space array
p=np.linspace(0,10,num=5)
p

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
# spacefic data types in array
i=np.ones(5,dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [31]:
j=np.ones(3,dtype=np.float64)
j

array([1., 1., 1.])

In [32]:
# 2D arrays

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [34]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 3D array


In [35]:
# makind and reshaping 3D Array
c=np.arange(24).reshape(2,3,4)# 2 matrix bnany h 3 row and 4 colmn
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# numpy practice session

# creating an array using numpy library

In [37]:
food=np.array(["samosa","pakora","raita"])
food

array(['samosa', 'pakora', 'raita'], dtype='<U6')

In [38]:
type(food)

numpy.ndarray

In [40]:
len(food)

3

In [41]:
food[0:]

array(['samosa', 'pakora', 'raita'], dtype='<U6')

In [42]:
food[2]

'raita'

In [43]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [45]:
np.linspace(0,20,num=5)

array([ 0.,  5., 10., 15., 20.])

In [50]:
np.ones(50,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [51]:
np.ones(50,dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# array functions

In [52]:
a=np.array([3.4,5,6,7,5.8,6.8])
a

array([3.4, 5. , 6. , 7. , 5.8, 6.8])

In [55]:
#sorting
a.sort()
a

array([3.4, 5. , 5.8, 6. , 6.8, 7. ])

In [56]:
b=np.array([3.4,5,6,7,2.8,7.8])
b

array([3.4, 5. , 6. , 7. , 2.8, 7.8])

In [57]:
c=np.concatenate((a,b))
c

array([3.4, 5. , 5.8, 6. , 6.8, 7. , 3.4, 5. , 6. , 7. , 2.8, 7.8])

In [58]:
c.sort()
c

array([2.8, 3.4, 3.4, 5. , 5. , 5.8, 6. , 6. , 6.8, 7. , 7. , 7.8])

In [60]:
x=np.array([[5,3],[2,4]])
x

array([[5, 3],
       [2, 4]])

In [61]:
y=np.array([[2,3],[2,1]])
y

array([[2, 3],
       [2, 1]])

In [64]:
np.concatenate((x,y),axis=0)

array([[5, 3],
       [2, 4],
       [2, 3],
       [2, 1]])

In [65]:
np.concatenate((x,y),axis=1)

array([[5, 3, 2, 3],
       [2, 4, 2, 1]])

In [66]:
a=np.array([[[0,1,2,3],[4,5,6,7]],[[3,5,7,6],[6,2,4,5]],[[5,3,9,8],[6,7,8,5]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[3, 5, 7, 6],
        [6, 2, 4, 5]],

       [[5, 3, 9, 8],
        [6, 7, 8, 5]]])

In [67]:
a.ndim

3

In [69]:
b=np.array([[0,1,2,3],[4,5,6,7],[3,5,7,6]])
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [3, 5, 7, 6]])

In [70]:
b.ndim

2

In [72]:
a.size

24

In [73]:
a.shape # dim,raws,colomn

(3, 2, 4)

In [75]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
np.reshape(a,newshape=(1,9),order='c')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [80]:
# convert 1D array into 2D array
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
a.shape

(9,)

In [85]:
# rows wise 2D conversion
b=a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [86]:
b.shape

(1, 9)

In [87]:
#column wise 2D conversion
c=a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [88]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
a[2:6]

array([3, 4, 5, 6])

In [90]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [91]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [92]:
a.sum()

45

In [93]:
a.mean()

5.0